export const BANK_CODES = [
    { code: '0100', name: 'Komerční banka, a.s.' },
    { code: '0300', name: 'Československá obchodní banka, a. s.' },
    { code: '0600', name: 'MONETA Money Bank, a.s.' },
    { code: '0710', name: 'Česká národní banka' },
    { code: '0800', name: 'Česká spořitelna, a.s.' },
    { code: '2010', name: 'Fio banka, a.s.' },
    { code: '2020', name: 'MUFG Bank (Europe) N.V. Prague Branch' },
    { code: '2030', name: 'Československé úvěrní družstvo' },
    { code: '2060', name: 'Citfin, spořitelní družstvo' },
    { code: '2070', name: 'TRINITY BANK a.s.' },
    { code: '2100', name: 'ČSOB Hypoteční banka, a.s.' },
    { code: '2200', name: 'Peněžní dům, spořitelní družstvo' },
    { code: '2220', name: 'Artesa, spořitelní družstvo' },
    { code: '2240', name: 'Poštová banka, a.s., pobočka Česká republika' },
    { code: '2250', name: 'Banka CREDITAS a.s.' },
    { code: '2260', name: 'NEY spořitelní družstvo' },
    { code: '2310', name: 'ZUNO AG, organizační složka' },
    { code: '2600', name: 'Citibank Europe plc, organizační složka' },
    { code: '2700', name: 'UniCredit Bank Czech Republic and Slovakia, a.s.' },
    { code: '3030', name: 'Air Bank a.s.' },
    { code: '3050', name: 'BNP Paribas Personal Finance SA, odštěpný závod' },
    { code: '3060', name: 'PKO BP S.A., Czech Branch' },
    { code: '3500', name: 'ING Bank N.V.' },
    { code: '4000', name: 'MAX banka a.s.' },
    { code: '4300', name: 'Národní rozvojová banka, a.s.' },
    { code: '5400', name: 'The Royal Bank of Scotland plc, organizační složka' },
    { code: '5500', name: 'Raiffeisenbank a.s.' },
    { code: '5800', name: 'J&T BANKA, a.s.' },
    { code: '6000', name: 'PPF banka a.s.' },
    { code: '6100', name: 'Equa bank a.s. (nyní Raiffeisenbank, a.s.)' },
    { code: '6200', name: 'COMMERZBANK Aktiengesellschaft, pobočka Praha' },
    { code: '6210', name: 'mBank S.A., organizační složka' },
    { code: '6300', name: 'BNP Paribas S.A., pobočka Česká republika' },
    { code: '6363', name: 'Partners Banka, a.s.' },
    {
        code: '6700',
        name: 'Všeobecná úverová banka a.s., pobočka Praha; zkráceně: VUB, a.s., pobočka Praha'
    },
    { code: '6800', name: 'Sberbank CZ, a.s.' },
    {
        code: '7910',
        name: 'Deutsche Bank Aktiengesellschaft Filiale Prag, organizační složka'
    },
    { code: '7940', name: 'Waldviertler Sparkasse Bank AG' },
    { code: '7950', name: 'Raiffeisen stavební spořitelna a.s.' },
    {
        code: '7960',
        name: 'ČSOB Stavební spořitelna, a.s. (Českomoravská stavební spořitelna a. s.)'
    },
    { code: '7970', name: 'MONETA Stavební Spořitelna, a.s.' },
    { code: '7980', name: 'Wüstenrot hypoteční banka' },
    { code: '7990', name: 'Modrá pyramida stavební spořitelna, a.s.' },
    { code: '8030', name: 'Volksbank Raiffeisenbank Nordoberpfalz eG pobočka Cheb' },
    { code: '8040', name: 'Oberbank AG pobočka Česká republika' },
    { code: '8060', name: 'Stavební spořitelna České spořitelny, a.s.' },
    { code: '8150', name: 'HSBC Continental Europe, Czech Republic' }
] as const;
