export enum EnergyFaceLabels {
    'Solární kolektor 1' = 1,
    //"Nezapojeno" = 3,
    'Akumulace nahoře' = 4,
    'Venkovní' = 5,
    'Topení teplá' = 6,
    'Nezapojeno' = 7,
    'M1' = 8,
    'M2' = 9,
    'Solar studená' = 10,
    'Akumulace dole' = 11,
    'Topení studená' = 12,
    //"nezapojeno" = 13,
    'Požadovaná teplota směšovacího ventilu' = 14,
    //"nezapojeno" = 15,
    //"nezapojeno" = 16,
    //"nezapojeno" = 17,
    //"nezapojeno" = 18,
    //"nezapojeno" = 19,
    'M3' = 20,
    'M4' = 21,
    'M5' = 22
}
