/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> =
    T extends ColumnType<infer S, infer I, infer U>
        ? ColumnType<S, I | undefined, U>
        : ColumnType<T, T | undefined, T>;

export interface Calendar {
    description: Generated<string | null>;
    from: Date;
    full_day: Buffer;
    id: Generated<number>;
    name: string;
    to: Date;
    user_id: number;
}

export interface DailyRoutine {
    day: number;
    home_arrival_time: Generated<number | null>;
    id: Generated<number>;
    transport_evening_time: Generated<number | null>;
    transport_evening_type: Generated<string | null>;
    transport_morning_time: Generated<number | null>;
    transport_morning_type: Generated<string | null>;
    user_id: number;
    wake_time: Generated<number | null>;
}

export interface Debt {
    id: Generated<number>;
    photo: Generated<string | null>;
    price: Decimal;
    resolved_on: Generated<Date | null>;
    when: Generated<Date>;
    who: number;
    whom: number;
}

export interface EnabledTempNotifications {
    userId: number;
}

export interface Group {
    bg_color: string;
    id: Generated<number>;
    name: string;
    text_color: string;
}

export interface GroupPermissions {
    group_id: number;
    permission: string;
}

export interface Invitation {
    code: string;
    created_at: Generated<Date>;
    id: Generated<number>;
    user_id: number;
}

export interface Route {
    day: number;
    direction: string; // 'morning' | 'evening'
    id: Generated<number>;
    user_id: number;
}

export interface RouteSegment {
    end_station: Generated<string | null>;
    end_time: Generated<number | null>;
    id: Generated<number>;
    position: number;
    route_id: number;
    start_station: Generated<string | null>;
    start_time: Generated<number | null>;
    transport_type: string; // 'bus' | 'car'
}

export interface Present {
    bought: Generated<number>;
    created_at: Generated<Date>;
    description: Generated<string | null>;
    id: Generated<number>;
    image: Generated<string | null>;
    link: Generated<string | null>;
    name: string;
    price: Decimal;
    reserved_id: Generated<number | null>;
    state: Generated<number>;
    updated_at: Generated<Date | null>;
    user_id: number;
}

export interface Shoppinglist {
    bought_at: Generated<Date | null>;
    bought_by: Generated<number | null>;
    count: number;
    created_at: Generated<Date>;
    id: Generated<number>;
    image: Generated<string | null>;
    name: string;
    user_id: number;
}

export interface TimetableEntry {
    day: number;
    end_min: number;
    id: Generated<number>;
    room: Generated<string | null>;
    start_min: number;
    subject: string;
    title: string;
    type: string;
    user_id: number;
}

export interface User {
    bank_account_number: Generated<string | null>;
    bank_account_prefix: Generated<string | null>;
    bank_code: Generated<string | null>;
    firstname: string;
    id: Generated<number>;
    lastname: string;
    password: string;
    username: string;
}

export interface UserGroup {
    group_id: number;
    user_id: number;
}

export interface WebPush {
    auth: string;
    endpoint: string;
    id: Generated<number>;
    p256dh: string;
    userId: number;
}

export interface SolarCooling {
    active_override: Generated<string | null>;
    down_temp: Generated<Decimal>;
    enabled: Generated<number>;
    freeze_target_temp: Generated<Decimal>;
    freeze_temp: Generated<Decimal>;
    id: Generated<number>;
    last_action: Generated<string | null>;
    last_action_at: Generated<Date | null>;
    max_temp: Generated<Decimal>;
    overheat_temp: Generated<Decimal>;
    updated_at: Generated<Date | null>;
}

export interface DB {
    calendar: Calendar;
    daily_routine: DailyRoutine;
    debt: Debt;
    enabled_temp_notifications: EnabledTempNotifications;
    group: Group;
    group_permissions: GroupPermissions;
    invitation: Invitation;
    present: Present;
    route: Route;
    route_segment: RouteSegment;
    shoppinglist: Shoppinglist;
    solar_cooling: SolarCooling;
    timetable_entry: TimetableEntry;
    user: User;
    user_group: UserGroup;
    web_push: WebPush;
}
