name: Deploy
on:
    push:
        branches:
            - main
jobs:
    build:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Execute command
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: ${{ secrets.PORT }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      cd /opt/NodeApps/FamilyApp

                      echo "Seting up nvm"                
                      export NVM_DIR="$HOME/.nvm"
                      source "$NVM_DIR/nvm.sh"
                      nvm use

                      echo "Pulling latest changes from git"
                      git pull

                      echo "Installing dependencies and building the app"
                      npm i
                      npm run build

                      echo "Restarting the app"
                      sudo systemctl restart family_app
                      echo "Deployment completed"
